# Generated by Django 2.1.4 on 2018-12-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
