# Generated by Django 2.1.4 on 2018-12-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitapp', '0002_tweet_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='updated',
        ),
    ]
